name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  google_geocoding_api: ^1.5.2
  http: ^1.2.2
  searchable_listview: ^2.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: game
      fonts:
        - asset: assets/fonts/Bitcount_Prop_Single/BitcountPropSingle-VariableFont_CRSV,ELSH,ELXP,slnt,wght.ttf